services:
  open-pi-sensor-fusion:
    image: open-pi-sensor-fusion-img
    container_name: open-pi-sensor-fusion
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    environment:
      RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
      ROS_DOMAIN_ID: ${ROS_DOMAIN_ID:-0}
